<script setup>
/**
 * AppIcon - Universal icon component replacing emojis with Heroicons SVGs.
 *
 * Usage:
 *   <AppIcon name="calendar" class="w-5 h-5" />
 *   <AppIcon name="calendar" :size="6" />
 *   <AppIcon name="calendar" solid />
 *
 * Props:
 *   name    - Icon name (lowercase, kebab-case), e.g. "calendar", "pencil-square"
 *   size    - Tailwind size number (4=w-4 h-4, 5=w-5 h-5, 6=w-6 h-6, etc.)
 *   solid   - Use solid variant (default: outline)
 */
import { computed, markRaw } from 'vue'

// Outline icons
import {
  HomeIcon,
  ChartBarIcon,
  PencilSquareIcon,
  PencilIcon,
  BoltIcon,
  DocumentIcon,
  DocumentTextIcon,
  DocumentDuplicateIcon,
  CalendarIcon,
  CalendarDaysIcon,
  BookOpenIcon,
  ArrowPathIcon,
  PhotoIcon,
  ClipboardDocumentListIcon,
  ClipboardDocumentIcon,
  AcademicCapIcon,
  FilmIcon,
  VideoCameraIcon,
  ScissorsIcon,
  TagIcon,
  ArrowUpTrayIcon,
  ArrowDownTrayIcon,
  MusicalNoteIcon,
  SparklesIcon,
  PresentationChartLineIcon,
  Cog6ToothIcon,
  PaintBrushIcon,
  CameraIcon,
  DevicePhoneMobileIcon,
  ChartBarSquareIcon,
  LightBulbIcon,
  QuestionMarkCircleIcon,
  ChatBubbleLeftRightIcon,
  ChatBubbleLeftIcon,
  EyeIcon,
  ClockIcon,
  GlobeAltIcon,
  GlobeEuropeAfricaIcon,
  MegaphoneIcon,
  StarIcon,
  HeartIcon,
  FireIcon,
  FaceSmileIcon,
  HandThumbUpIcon,
  RocketLaunchIcon,
  CheckCircleIcon,
  XCircleIcon,
  XMarkIcon,
  BellIcon,
  BellAlertIcon,
  ArchiveBoxIcon,
  InboxIcon,
  InboxStackIcon,
  LockClosedIcon,
  LockOpenIcon,
  KeyIcon,
  ShieldCheckIcon,
  TrophyIcon,
  PaperAirplaneIcon,
  FolderIcon,
  FolderOpenIcon,
  ShareIcon,
  LinkIcon,
  HashtagIcon,
  TrashIcon,
  PlusIcon,
  PlusCircleIcon,
  MagnifyingGlassIcon,
  AdjustmentsHorizontalIcon,
  AdjustmentsVerticalIcon,
  ArrowTrendingUpIcon,
  MicrophoneIcon,
  SpeakerWaveIcon,
  PlayIcon,
  PauseIcon,
  StopIcon,
  MapPinIcon,
  UserIcon,
  UserGroupIcon,
  Squares2X2Icon,
  QueueListIcon,
  ListBulletIcon,
  RectangleStackIcon,
  ArrowsPointingOutIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  HandRaisedIcon,
  BookmarkIcon,
  SwatchIcon,
  TableCellsIcon,
  ComputerDesktopIcon,
  WrenchScrewdriverIcon,
  FunnelIcon,
  CloudArrowUpIcon,
  LanguageIcon,
  PrinterIcon,
  Bars3Icon,
} from '@heroicons/vue/24/outline'

// Solid icons
import {
  ChartBarIcon as ChartBarSolid,
  PencilSquareIcon as PencilSquareSolid,
  BoltIcon as BoltSolid,
  DocumentIcon as DocumentSolid,
  DocumentTextIcon as DocumentTextSolid,
  CalendarIcon as CalendarSolid,
  CalendarDaysIcon as CalendarDaysSolid,
  BookOpenIcon as BookOpenSolid,
  PhotoIcon as PhotoSolid,
  AcademicCapIcon as AcademicCapSolid,
  FilmIcon as FilmSolid,
  VideoCameraIcon as VideoCameraSolid,
  TagIcon as TagSolid,
  MusicalNoteIcon as MusicalNoteSolid,
  SparklesIcon as SparklesSolid,
  Cog6ToothIcon as Cog6ToothSolid,
  PaintBrushIcon as PaintBrushSolid,
  CameraIcon as CameraSolid,
  DevicePhoneMobileIcon as DevicePhoneMobileSolid,
  LightBulbIcon as LightBulbSolid,
  GlobeAltIcon as GlobeAltSolid,
  StarIcon as StarSolid,
  HeartIcon as HeartSolid,
  FireIcon as FireSolid,
  CheckCircleIcon as CheckCircleSolid,
  XCircleIcon as XCircleSolid,
  BellIcon as BellSolid,
  TrophyIcon as TrophySolid,
  MegaphoneIcon as MegaphoneSolid,
  PresentationChartLineIcon as PresentationChartLineSolid,
  ClipboardDocumentListIcon as ClipboardDocumentListSolid,
  EyeIcon as EyeSolid,
  ClockIcon as ClockSolid,
  KeyIcon as KeySolid,
  LockClosedIcon as LockClosedSolid,
  ArchiveBoxIcon as ArchiveBoxSolid,
  InboxIcon as InboxSolid,
  ArrowUpTrayIcon as ArrowUpTraySolid,
  ScissorsIcon as ScissorsSolid,
  MicrophoneIcon as MicrophoneSolid,
  QuestionMarkCircleIcon as QuestionMarkCircleSolid,
  ChatBubbleLeftRightIcon as ChatBubbleLeftRightSolid,
  FaceSmileIcon as FaceSmileSolid,
  HandThumbUpIcon as HandThumbUpSolid,
  RocketLaunchIcon as RocketLaunchSolid,
} from '@heroicons/vue/24/solid'

const props = defineProps({
  name: { type: String, required: true },
  size: { type: [Number, String], default: null },
  solid: { type: Boolean, default: false },
})

// Outline icon map
const outlineMap = {
  'home': HomeIcon,
  'chart-bar': ChartBarIcon,
  'dashboard': ChartBarIcon,
  'pencil': PencilIcon,
  'pencil-square': PencilSquareIcon,
  'edit': PencilSquareIcon,
  'bolt': BoltIcon,
  'lightning': BoltIcon,
  'quick': BoltIcon,
  'document': DocumentIcon,
  'drafts': DocumentIcon,
  'document-text': DocumentTextIcon,
  'document-duplicate': DocumentDuplicateIcon,
  'calendar': CalendarIcon,
  'calendar-days': CalendarDaysIcon,
  'campaign': CalendarDaysIcon,
  'book-open': BookOpenIcon,
  'story': BookOpenIcon,
  'arrow-path': ArrowPathIcon,
  'refresh': ArrowPathIcon,
  'recurring': ArrowPathIcon,
  'photo': PhotoIcon,
  'image': PhotoIcon,
  'assets': PhotoIcon,
  'clipboard-list': ClipboardDocumentListIcon,
  'clipboard': ClipboardDocumentIcon,
  'posts': ClipboardDocumentListIcon,
  'academic-cap': AcademicCapIcon,
  'students': AcademicCapIcon,
  'graduation': AcademicCapIcon,
  'film': FilmIcon,
  'video': FilmIcon,
  'thumbnails': FilmIcon,
  'video-camera': VideoCameraIcon,
  'overlay': VideoCameraIcon,
  'scissors': ScissorsIcon,
  'cut': ScissorsIcon,
  'tag': TagIcon,
  'branding': TagIcon,
  'label': TagIcon,
  'arrow-up-tray': ArrowUpTrayIcon,
  'upload': ArrowUpTrayIcon,
  'export': ArrowUpTrayIcon,
  'arrow-down-tray': ArrowDownTrayIcon,
  'download': ArrowDownTrayIcon,
  'musical-note': MusicalNoteIcon,
  'music': MusicalNoteIcon,
  'audio': MusicalNoteIcon,
  'tiktok': MusicalNoteIcon,
  'sparkles': SparklesIcon,
  'ai': SparklesIcon,
  'magic': SparklesIcon,
  'brain': SparklesIcon,
  'presentation-chart': PresentationChartLineIcon,
  'analytics': PresentationChartLineIcon,
  'trending-up': ArrowTrendingUpIcon,
  'cog': Cog6ToothIcon,
  'settings': Cog6ToothIcon,
  'paint-brush': PaintBrushIcon,
  'design': PaintBrushIcon,
  'camera': CameraIcon,
  'feed': CameraIcon,
  'instagram': CameraIcon,
  'device-mobile': DevicePhoneMobileIcon,
  'mobile': DevicePhoneMobileIcon,
  'phone': DevicePhoneMobileIcon,
  'chart-bar-square': ChartBarSquareIcon,
  'infographic': ChartBarIcon,
  'light-bulb': LightBulbIcon,
  'tips': LightBulbIcon,
  'idea': LightBulbIcon,
  'question-mark-circle': QuestionMarkCircleIcon,
  'faq': QuestionMarkCircleIcon,
  'help': QuestionMarkCircleIcon,
  'chat-bubble': ChatBubbleLeftRightIcon,
  'chat': ChatBubbleLeftRightIcon,
  'testimonial': ChatBubbleLeftRightIcon,
  'experience': ChatBubbleLeftRightIcon,
  'chat-left': ChatBubbleLeftIcon,
  'eye': EyeIcon,
  'behind-scenes': EyeIcon,
  'look': EyeIcon,
  'clock': ClockIcon,
  'time': ClockIcon,
  'deadline': ClockIcon,
  'hourglass': ClockIcon,
  'globe': GlobeAltIcon,
  'world': GlobeAltIcon,
  'countries': GlobeAltIcon,
  'globe-europe': GlobeEuropeAfricaIcon,
  'megaphone': MegaphoneIcon,
  'cta': MegaphoneIcon,
  'announce': MegaphoneIcon,
  'star': StarIcon,
  'favorite': StarIcon,
  'heart': HeartIcon,
  'love': HeartIcon,
  'emotional': HeartIcon,
  'wholesome': HeartIcon,
  'fire': FireIcon,
  'energy': FireIcon,
  'hot': FireIcon,
  'trending': FireIcon,
  'face-smile': FaceSmileIcon,
  'smile': FaceSmileIcon,
  'humor': FaceSmileIcon,
  'witty': FaceSmileIcon,
  'thumb-up': HandThumbUpIcon,
  'motivate': HandThumbUpIcon,
  'strong': HandThumbUpIcon,
  'rocket': RocketLaunchIcon,
  'launch': RocketLaunchIcon,
  'check-circle': CheckCircleIcon,
  'success': CheckCircleIcon,
  'done': CheckCircleIcon,
  'x-circle': XCircleIcon,
  'error': XCircleIcon,
  'fail': XCircleIcon,
  'x-mark': XMarkIcon,
  'close': XMarkIcon,
  'bell': BellIcon,
  'notification': BellIcon,
  'reminder': BellIcon,
  'bell-alert': BellAlertIcon,
  'archive': ArchiveBoxIcon,
  'box': ArchiveBoxIcon,
  'package': ArchiveBoxIcon,
  'inbox': InboxIcon,
  'inbox-stack': InboxStackIcon,
  'lock': LockClosedIcon,
  'locked': LockClosedIcon,
  'secure': LockClosedIcon,
  'lock-open': LockOpenIcon,
  'key': KeyIcon,
  'access': KeyIcon,
  'shield': ShieldCheckIcon,
  'trophy': TrophyIcon,
  'achievement': TrophyIcon,
  'award': TrophyIcon,
  'paper-airplane': PaperAirplaneIcon,
  'send': PaperAirplaneIcon,
  'travel': PaperAirplaneIcon,
  'airplane': PaperAirplaneIcon,
  'folder': FolderIcon,
  'folder-open': FolderOpenIcon,
  'share': ShareIcon,
  'link': LinkIcon,
  'hashtag': HashtagIcon,
  'trash': TrashIcon,
  'delete': TrashIcon,
  'plus': PlusIcon,
  'add': PlusIcon,
  'plus-circle': PlusCircleIcon,
  'search': MagnifyingGlassIcon,
  'adjustments': AdjustmentsHorizontalIcon,
  'adjustments-vertical': AdjustmentsVerticalIcon,
  'slider': AdjustmentsVerticalIcon,
  'microphone': MicrophoneIcon,
  'voice': MicrophoneIcon,
  'speaker': SpeakerWaveIcon,
  'play': PlayIcon,
  'pause': PauseIcon,
  'stop': StopIcon,
  'map-pin': MapPinIcon,
  'location': MapPinIcon,
  'user': UserIcon,
  'user-group': UserGroupIcon,
  'grid': Squares2X2Icon,
  'queue': QueueListIcon,
  'list': ListBulletIcon,
  'stack': RectangleStackIcon,
  'expand': ArrowsPointingOutIcon,
  'warning': ExclamationTriangleIcon,
  'info': InformationCircleIcon,
  'hand-raised': HandRaisedIcon,
  'bookmark': BookmarkIcon,
  'swatch': SwatchIcon,
  'palette': SwatchIcon,
  'table': TableCellsIcon,
  'desktop': ComputerDesktopIcon,
  'wrench': WrenchScrewdriverIcon,
  'tools': WrenchScrewdriverIcon,
  'funnel': FunnelIcon,
  'filter': FunnelIcon,
  'cloud-upload': CloudArrowUpIcon,
  'printer': PrinterIcon,
  'print': PrinterIcon,
  'events': StarIcon,
  'celebration': TrophyIcon,
  'confetti': TrophyIcon,
  'party': TrophyIcon,
  'personality': UserIcon,
  'theater': UserGroupIcon,
  'nerd': AcademicCapIcon,
  'library': BookOpenIcon,
  'series': BookOpenIcon,
  'script': DocumentTextIcon,
  'language': LanguageIcon,
  'text-input': LanguageIcon,
  'bars-3': Bars3Icon,
  'menu': Bars3Icon,
  'align-center': Bars3Icon,
}

// Solid icon map
const solidMap = {
  'chart-bar': ChartBarSolid,
  'dashboard': ChartBarSolid,
  'pencil-square': PencilSquareSolid,
  'edit': PencilSquareSolid,
  'bolt': BoltSolid,
  'lightning': BoltSolid,
  'quick': BoltSolid,
  'document': DocumentSolid,
  'drafts': DocumentSolid,
  'document-text': DocumentTextSolid,
  'calendar': CalendarSolid,
  'calendar-days': CalendarDaysSolid,
  'campaign': CalendarDaysSolid,
  'book-open': BookOpenSolid,
  'story': BookOpenSolid,
  'photo': PhotoSolid,
  'image': PhotoSolid,
  'assets': PhotoSolid,
  'academic-cap': AcademicCapSolid,
  'students': AcademicCapSolid,
  'film': FilmSolid,
  'video': FilmSolid,
  'video-camera': VideoCameraSolid,
  'tag': TagSolid,
  'branding': TagSolid,
  'musical-note': MusicalNoteSolid,
  'music': MusicalNoteSolid,
  'tiktok': MusicalNoteSolid,
  'sparkles': SparklesSolid,
  'ai': SparklesSolid,
  'magic': SparklesSolid,
  'brain': SparklesSolid,
  'presentation-chart': PresentationChartLineSolid,
  'analytics': PresentationChartLineSolid,
  'cog': Cog6ToothSolid,
  'settings': Cog6ToothSolid,
  'paint-brush': PaintBrushSolid,
  'design': PaintBrushSolid,
  'camera': CameraSolid,
  'feed': CameraSolid,
  'instagram': CameraSolid,
  'device-mobile': DevicePhoneMobileSolid,
  'mobile': DevicePhoneMobileSolid,
  'light-bulb': LightBulbSolid,
  'tips': LightBulbSolid,
  'globe': GlobeAltSolid,
  'countries': GlobeAltSolid,
  'star': StarSolid,
  'favorite': StarSolid,
  'heart': HeartSolid,
  'love': HeartSolid,
  'fire': FireSolid,
  'energy': FireSolid,
  'face-smile': FaceSmileSolid,
  'humor': FaceSmileSolid,
  'thumb-up': HandThumbUpSolid,
  'motivate': HandThumbUpSolid,
  'rocket': RocketLaunchSolid,
  'check-circle': CheckCircleSolid,
  'success': CheckCircleSolid,
  'x-circle': XCircleSolid,
  'error': XCircleSolid,
  'bell': BellSolid,
  'notification': BellSolid,
  'trophy': TrophySolid,
  'achievement': TrophySolid,
  'megaphone': MegaphoneSolid,
  'cta': MegaphoneSolid,
  'clipboard-list': ClipboardDocumentListSolid,
  'posts': ClipboardDocumentListSolid,
  'eye': EyeSolid,
  'clock': ClockSolid,
  'key': KeySolid,
  'lock': LockClosedSolid,
  'archive': ArchiveBoxSolid,
  'inbox': InboxSolid,
  'export': ArrowUpTraySolid,
  'scissors': ScissorsSolid,
  'microphone': MicrophoneSolid,
  'question-mark-circle': QuestionMarkCircleSolid,
  'faq': QuestionMarkCircleSolid,
  'chat-bubble': ChatBubbleLeftRightSolid,
  'testimonial': ChatBubbleLeftRightSolid,
}

const iconComponent = computed(() => {
  const map = props.solid ? solidMap : outlineMap
  const component = map[props.name]
  if (component) return markRaw(component)
  // Fallback: try outline map even if solid requested
  if (props.solid && outlineMap[props.name]) return markRaw(outlineMap[props.name])
  // Ultimate fallback: question mark
  return markRaw(QuestionMarkCircleIcon)
})

const sizeClass = computed(() => {
  if (!props.size) return ''
  return `w-${props.size} h-${props.size}`
})
</script>

<template>
  <component :is="iconComponent" :class="sizeClass" />
</template>
